export const PcLocators = {
  urls: {
    myPage: 'https://www.kshop.co.kr/custord/mypage/auth/main',
    onAirGiftOrder: 'custord/present/orderSheet',
    onAirBuyOrder: 'custord/orderSheet',
    productDetail: 'display/product',
    myLikePage: 'https://www.kshop.co.kr/display/shoppingHistory/product?tab=like',
    giftShowGiftOrder: 'custord/giftishowDecorate',
    giftShowPaymentOrder: 'custord/giftishowOrderSheet',
  },
  main: {
    navItems: '//nav//li',
    mainArea: '//main',
    onAirButton: '//button[contains(@class,"FloatingBannerActions_btnOnAirLottie")]',
    onAirDisplay: '//div[contains(@class,"OnAirDisplay_wrap")]',
    onAirDirectBuyButton: '//div[contains(@class,"OnAirProgram_btnArea")]//span[contains(text(),"바로구매")]',
    onAirDirectBuyFirstOption: '//div[contains(@class,"SelectBox_optionList")]/*[self::button or self::div]',
    onAirDirectBuySecondOption: '//button[contains(@class,"SelectBox_option")]',
    onAirGiftButton: '//div[contains(@class,"ButtonPurchase")]//span[text()="선물하기"]',
    onAirProductName: '//a[contains(@class,"OnAirProgram_title")]',
    onAirCartButton: '//div[contains(@class,"ButtonPurchase")]//span[text()="장바구니"]',
    onAirCartMoveButton: '//span[text()="바로가기"]',
    cartProductName: '(//button[contains(@class,"OrderProductItem_prodName")])[last()]',
    cartDeleteButton: '//span[text()="선택 삭제"]',
    cartRecommendProduct: '(//div[contains(@class,"MyCart_recommend")]//div[contains(@class,"ProductItem_box")])[1]',
    onAirBuyButton: '//div[contains(@class,"ButtonPurchase")]//span[text()="구매하기"]',
    categoryButton: '//button[text()="카테고리"]',
    homeShoppingOneDepthButton: '//div[contains(@class,"Modal")]//div[contains(@class,"Tab_wrap")]/div/button[1]',
    categoryTwoDepthButton: '//div[contains(@class,"categoryList")]/a',
    homeShoppingThreeDepthButton: '//div[contains(@class,"SubCategoryMenu_inner")]/button',
    firstFilterButton: '(//ul[contains(@class,"sortList")]/li/button)[1]',
    productQuantity: '//div[contains(@class,"listHeader")]/strong',
    searchButton: '//div[contains(@class,"Header_right")]/a',
    popularWords: '//ul[contains(@class,"PopularWords")]//p',
    searchProduct: '(//div[contains(@class,"ProductItem_box")]//a)[1]',
    recentlyViewedProduct: '((//div[contains(@class,"ProductDisplay_section")])[1]//div[contains(@class,"ProductItem_box")])[1]',
    searchInput: '//div[contains(@class,"searchInput")]/input',
    searchSubmitButton: '//div[contains(@class,"Search_search")]//button[@type="submit"]',
    categoryProduct: '(//div[contains(@class,"CategoryDetailPage_productList")]//div[contains(@class,"ProductItem_box")])[1]',
    backButton: '//div[contains(@class,"Header_back")]',
    recommendProduct: '(//div[contains(@class,"RecommendDisplay_wrap")]//div[contains(@class,"ProductItem_box")])[1]',
    searchRecommendProduct: '(//div[contains(@class,"SearchResult_topLineBox")][2]//div[contains(@class,"ProductItem_box")])[1]',
    productSection: '//div[contains(@class,"displayWrap")][6]',
    product: '(//div[contains(@class,"displayWrap")][6]//div[contains(@class,"ProductItem_box")])[1]',
    tvPlusTab: '//div[contains(@class,"LiveTimeLine_liveSelect")]//button[2]',
    benefitTab: '//strong[contains(text(),"혜택/이벤트")]',
    benefitTitle: '//h1[contains(@class,"Header_title")]',
    newSignBenefitTab: '(//div[contains(@class,"BenefitIconSwiper_wrap")])[1]/div[2]//div[contains(@class,"swiper-slide")][1]',
    monthGiftTab: '(//div[contains(@class,"BenefitIconSwiper_wrap")])[1]/div[2]//div[contains(@class,"swiper-slide")][2]',
    membershipBenefitTab: '(//div[contains(@class,"BenefitIconSwiper_wrap")])[1]/div[2]//div[contains(@class,"swiper-slide")][3]',
    agreeReceiveTab: '(//div[contains(@class,"BenefitIconSwiper_wrap")])[1]/div[2]//div[contains(@class,"swiper-slide")][4]',
  },
  login: {
    loginButton: '//a[text()="로그인/회원 가입"]',
    idInput: '//input[@placeholder="아이디"]',
    pwInput: '//input[@placeholder="비밀번호"]',
    loginSubmitButton: '//span[text()="로그인"]',
    logoutButton: '//button[text()="로그아웃"]',
    certificationRequestButton: '//span[text()="인증요청"]',
  },
  product: {
    onAirVideoPoster: '//div[contains(@class,"ModalOnAir_poster")]',
    onAirVideo: '//div[contains(@class,"ModalOnAir_videoBox")]//video',
    alarmButton: '//button[contains(@class,"OnAirProgram_btnAlarm")]',
    broadcastNotificationRegisterButton: '//span[text()="방송 알림 등록하기"]',
    smsConsentCheckbox: '(//label[contains(@class,"checkbox")])[1]',
    myBroadcastNotificationButton: '//span[text()="내 방송알림보기"]',
    disableNotificationButton: '//span[text()="알림 해제"]',
    mdsPickSection: '//div[contains(@class,"displayWrap")][5]',
    mdsPickProduct: '//div[contains(@class,"HeroBannerC_frame")]',
    productLikeButton: '(//div[contains(@class,"ProdActions_support")]//button)[1]',
    likePageLikeButton: '//div[contains(@class,"ProductItem_box")]/button',
    productDetailInfoTab: '(//div[contains(@class,"ProductTemplate_tab")]//button)[1]',
    productDetailInfo: '//div[contains(@class,"ProdDetailInfo_wrap") or contains(@class,"CombinedProductList_wrap")]',
    productBuyInfoTab: '(//div[contains(@class,"ProductTemplate_tab")]//button)[2]',
    productBuyInfo: '//div[contains(@class,"BuyDetailInfo_wrap")]',
    productReviewTab: '(//div[contains(@class,"ProductTemplate_tab")]//button)[3]',
    productQnaTab: '(//div[contains(@class,"ProductTemplate_tab")]//button)[4]',
    productReview: '//div[contains(@class,"ReviewDetailInfo_wrap")]',
    productQna: '//div[contains(@class,"ProdQnaDetail_wrap")]',
    optionBox: '//div[contains(@class,"SelectBox_item")]',
    productName: '//div[contains(@class,"ProdTopInfo_title")]//strong',
    recommendProduct: '(//div[contains(@class,"ProdDetailInfo")][3]//div[contains(@class,"ProductItem_box")])[1]',
  },
  quick: {
    onAirModalImg: '//button[contains(@class,"ModalOnAir")]//img',
    onAirDirectBuyButton: '//div[contains(@class,"ModalOnAir_buyBox")]//button',
    onAirProductName: '//div[contains(@class,"ModalOnAir_inner")]//em[contains(@class,"ProductItem_title")]',
  },
  my: {
    myButton: '//a[text()="마이"]',
    orderHistoryTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[1]',
    orderList: '//div[contains(@class,"orderList")]',
    claimHistoryTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[2]',
    giftShowTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[3]',
    giftShowContent: '//div[contains(@class,"GiftShowPage_wrap")]',
    giftShowBalanceTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[4]',
    giftShowBalanceContent: '//div[contains(@class,"GiftShowBalanceTemplate_wrap")]',
    taxListTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[5]',
    taxListContent: '//div[contains(@class,"TaxListTemplate_wrap")]',
    deliveryAddressTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[1]',
    deliveryAddressContent: '//div[contains(@class,"addressList")]',
    phoneAddressTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[2]',
    phoneAddressContent: '//div[contains(@class,"PhoneAddress_wrap")]',
    refundAccountTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[3]',
    refundAccountContent: '//div[contains(@class,"RefundAccountList_wrap")]',
    giftMessageTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[4]',
    giftMessageContent: '//div[contains(@class,"GiftMessageMangmentTemplate_wrap")]',
    alphaPointTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[5]',
    alphaPointContent: '//div[contains(@class,"AlphaPoint_box")]',
    ticketTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[6]',
    ticketContent: '//div[contains(@class,"Ticket_box")]',
    broadcastNotificationTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[7]',
    broadcastNotificationContent: '//div[contains(@class,"NotificationList")]',
    simpleLoginTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[8]',
    simpleLoginContent: '//ul[contains(@class,"simpleLoginList")]',
    modifyCustomerInfoTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[9]',
    nameInput: '//input[@placeholder="이름"]',
    nextButton: '//div[contains(@class,"ButtonGroup")]/button',
    maleButton: '//div[contains(@class,"RadioButtonGroup_group")]/label[2]',
    yearInput: '(//div[contains(@class,"TextInputWrap")]//div[contains(@class,"TextInput_field")]/input)[1]',
    monthInput: '(//div[contains(@class,"TextInputWrap")]//div[contains(@class,"TextInput_field")]/input)[2]',
    dayInput: '(//div[contains(@class,"TextInputWrap")]//div[contains(@class,"TextInput_field")]/input)[3]',
    ktAgencyButton: '//ul[contains(@class,"AgencySelect")]/li[1]',
    phoneNumberInput: '//input[@placeholder="숫자만 입력"]',
    modifyCustomerInfoContent: '//div[contains(@class,"ModifyCustInfo_wrap")]',
    benefitTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[10]',
    cartTab: '//div[contains(@class,"MyPage_menuList")]/div[3]//li[1]',
    cartContent: '//div[contains(@class,"MyCart_productList")]',
    likeTab: '//div[contains(@class,"MyPage_menuList")]/div[3]//li[2]',
    likeContent: '//div[contains(@class,"tabContainer")]',
    reviewTab: '//div[contains(@class,"MyPage_menuList")]/div[3]//li[3]',
    reviewContent: '//div[contains(@class,"tabContainer")]',
    recentlyTab: '//div[contains(@class,"MyPage_menuList")]/div[3]//li[4]',
    recentlyContent: '//div[contains(@class,"tabContainer")]',
    inquiryTab: '//div[contains(@class,"MyPage_menuList")]/div[4]//li[1]',
    inquiryContent: '//div[contains(@class,"PersonalInquiryForm_wrap")]',
    inquiryListTab: '//div[contains(@class,"MyPage_menuList")]/div[4]//li[2]',
    inquiryListContent: '//div[contains(@class,"CustomerInquiryList")]',
    noticeTab: '//div[contains(@class,"MyPage_menuList")]/div[4]//li[3]',
    noticeContent: '//div[contains(@class,"AccordionBox_wrap")]',
    faqTab: '//div[contains(@class,"MyPage_menuList")]/div[4]//li[4]',
    faqContent: '//div[contains(@class,"FaqTemplate_wrap")]',
  },
  giftShowMain: {
    giftShowOneDepthButton: '//div[contains(@class,"Modal")]//div[contains(@class,"Tab_wrap")]/div/button[2]',
    giftShowThreeDepthButton: '//ul[contains(@class,"Brands_list")]/li',
    firstButtonInFilter : '(//ul[contains(@class,"ModalCategoryFilter_btnRadio")]/li/button)[1]',
    filterSearchButton : '//div[contains(@class,"ModalCategoryFilter_buttonGroup")]/button[2]',
    giftProduct: '(//div[contains(@class,"ProductItem_item")])[1]',
  },
  giftShowProduct: {
    giftProduct: '(//div[contains(@class,"ProductItem_item")])[1]',
    sendToMeButton: '//div[contains(@class,"ButtonPurchase_inner")]//span[text()="나에게 보내기"]',
    giftShowMainPhoneNumberButton: '(//div[contains(@class,"OrderSheetGiftshow_inner")])[1]//label[2]',
    senderInput: '//div[contains(@class,"OrderSheetGiftshow_sender")]//input',
    myPhoneNumberButton: '((//div[contains(@class,"OrderSheetGiftshow_inner")])[1]//label)[1]',
    recipientPhoneNumberInput: '((//div[contains(@class,"GiftshowAddContact_recipientItem")]/div)[1]//input)[1]',
    recipientNameInput: '((//div[contains(@class,"GiftshowAddContact_recipientItem")]/div)[1]//input)[2]',
    totalRecipients: '//ul[contains(@class,"totalPriceList")]/li[1]/strong',
    paymentButton: '(//div[contains(@class,"ButtonPurchase_inner")])[1]',
  }
};
